# Generated by Django 3.1.13 on 2021-11-23 11:39

from django.db import migrations, models
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='day',
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(default=todos.models.getday, max_length=50, unique=True),
        ),
    ]
