# Generated by Django 3.1.13 on 2021-11-23 12:18

from django.db import migrations, models
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20211123_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(default=todos.models.getday, max_length=50),
        ),
    ]
